Restore old pull_request action

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -2,23 +2,22 @@ name: pull_request
 
 permissions:
   pull-requests: write
-  checks: write
-  contents: read
 
 
 on:
   workflow_call:
 
 jobs:
+  #scons:
+    #if: ()"!contains(github.event.pull_request.labels.*.name, 'notForAddon')") ||  (github.event.comment.body == 'run action') && (github.event.issue.pull_request)
   scons:
-    if: "!contains(github.event.pull_request.labels.*.name, 'notForAddon') || !contains(github.event.pull_request.labels.*.name, 'translation')"
+    if: github.event.comment.body == 'run action' && github.event.issue.pull_request
     runs-on: ubuntu-latest
     steps:
       - name: Checkout source repository
         uses: actions/checkout@v4
         with:
-          ref: ${{ github.event.pull_request.head.ref }}
-          
+          ref: refs/pull/${{ github.event.issue.number }}/head
       - name: Set up Python 3.11
         uses: actions/setup-python@v5
         with:
@@ -35,39 +34,35 @@ jobs:
 
       - name: get commit hash
         run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
-
       - name: build with hash of commit
-        run: scons version=$COMMIT_HASH 2> build_error.log
-
+        run: scons version=$COMMIT_HASH 2> build_error.log        
       - name: upload artifacts
-        if: success()
         uses: actions/upload-artifact@v4
         id: artifactURL
+        if: success()
         with:
           name: build-artifact
           path: ./*.nvda-addon
-
-      - name: Add check
-        if: success()
-        uses: LouisBrunner/checks-action@v2.0.0
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          name: Add-on build
-          conclusion: ${{ job.status }}
-          output: |
-            {"summary":"Add-on built sucessfully, download here: ${{ steps.artifactURL.outputs.artifactURL }}"}
-
-      - name: Comment on PR if build fails
-        if: failure()
+          
+      - name: comment on pull request
         uses: actions/github-script@v7
+        if: always()
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
             const fs = require('fs');
-            const errorMessage = fs.readFileSync('build_error.log', 'utf8');
+            let body;
+            
+            if (fs.existsSync('build_error.log') && fs.statSync('build_error.log').size > 2) {
+              const errorMessage = fs.readFileSync('build_error.log', 'utf8');
+              body = `Add-on build failed with error:\n ${errorMessage}`;
+            } else if (${{steps.artifactURL}}) {
+              body = `Add-on built successfully. [Download here](${{steps.artifactURL.outputs.artifact-url}})`;
+            }
+            
             github.rest.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
-              body: `Add-on build failed with error:\n\`\`\`\n${errorMessage}\n\`\`\``
+              body: body
             });
